### ISSUE TITLE
Any options to drop requests that out of limit?

### ISSUE THREAD

**Issue by Misaka-0x447f** [leviwheatcroft/superagent-throttle#15]

**Comment by leviwheatcroft** [comment]
can you explain "out of limit" ? do you mean you just want to discard requests which are overthe api limit rather than queuing them ?

There's no option for that.

**Comment by Misaka-0x447f** [comment]
okay I just means you can set a number and if pending request count is higher than that then any new requests will be drop.

Yeah that could be a feature request not a question...........
Also, I did this using another way so anyway thanks for responding.
