### ISSUE TITLE
Sometimes requests just randomly stop being sent

### ISSUE THREAD

**Issue by IcarusCodes** [leviwheatcroft/superagent-throttle#16]
Hello,

I am running an API check for gathering data as part of an Web Automation Test and I find the throttle plugin to be very useful. I've done some performance/load testing on the environment using locust.io and concluded that it handles up to 25-30 Requests per second, therefore I've set my throttle to 10 concurrent requests/s. I am using mocha as my preferred framework in tandem with superagent and superagent-throttle to perform my requests.

The issue I encounter is that the requests stop being sent at random times. I am sending 13k requests in total, and sometimes it randomly stops at 3k sometimes at 7k, sometimes it goes through completely.

I'm using Mac OS X High Sierra 10.13.2, the server is nginx/1.10.3 (Ubuntu). Node 8.9.1, npm 5.6.0, mocha 5.0.1, superagent-throttle 0.2.5;

I am just curious if I am doing something wrong in my code and in my throttle declaration, If however you did not encounter this issue and the code appears fine you can safely close the issue.

Thank you in advance!
Stoian Alex

```
// >>> Dependency Declarations
const fs                = require('fs');
const colors            = require('colors');
const request 		= require('superagent');
const Throttle 	 	= require('superagent-throttle');
const allLocalities     = require('./data/allLocalities.json');


// >>> Forces the connection without a secure certificate
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// >>> The url on which we test + our API path
const endpoint = process.env.url + '/api/localities/isProductAvailableInLocality';


// >> We throttle our requests in order not to overload the server
let throttle = new Throttle({
  active: true,       // set false to pause queue
  rate: 10,           // how many requests can be sent every `ratePer`
  ratePer: 1000,      // number of ms in which `rate` requests may be sent
  concurrent: 10      // how many requests can be sent concurrently
});


// >>> A function that checks if the locality hasElectricity and if it hasGas
function checkAvailability() {
	var allLocalitiesAndProducts = [];
	for (let i = 0; i < allLocalities.length; i++) {
		request
		.post(endpoint, {"localityId": allLocalities[i].locNr, "productId": 1})
		.use(throttle.plugin())
		.end((err, res) => { 
			allLocalitiesAndProducts.push({
				"Response": res.body
			})
			console.log(res.body); // #debug
			fs.writeFileSync(`./data/productAvailability.json`, JSON.stringify(allLocalitiesAndProducts), "UTF-8");
		});
	}
}


// >>> Script Start
checkAvailability();
```

**Comment by leviwheatcroft** [comment]
Sorry I missed this.

Earlier versions of `superagent-throttle` had issues clearing out "timed out" requests, so you would've seen exactly this behaviour. You start with 10 concurrent requests, but with each timeout you'd lose one slot, until you had none and then it'd just stop.

However, this was resolved in the version published at the time you posted this comment.

So, if you're still seeing this behaviour update to current version, then let me know and I'll take a look at it.

I'm gonna close this for now but feel free to re-open.

**Comment by esetnik** [comment]
I believe i'm having the same problem in the current version. Randomly it seems that end is not called for all of my throttled requests.
