### ISSUE TITLE
Superagent's not returning instance

### ISSUE THREAD

**Issue by zenorocha** [leviwheatcroft/superagent-throttle#2]
Before applying the plugin I could run methods based on the returned instance of superagent.

``` js
var req = superagent.get(something);
req.abort();
```

But after using the plugin, it tells me that what returned is undefined.

Any tips on how to overcome that? Thanks!

**Comment by leviwheatcroft** [comment]
No worries, if I had to guess I'd say the plugin just needs to return the superagent instance right after [this](https://github.com/leviwheatcroft/superagent-throttle/blob/master/index.js#L165) line. 

Hopefully I'll be able to push a patch within the next 18 hours or so.

**Comment by leviwheatcroft** [comment]
I just pushed v0.0.6 to npm which solves #1, but I also made the change I mentioned above. Sorry but I just don't have time right now to test whether or not this will solve your issue. If you can test for me I'd really appreciate it. If it doesn't work, do you think you could give me an example of something that doesn't work? Like a small variation on the usage example included in readme.md?

Thanks mate.

**Comment by zenorocha** [comment]
Sure. 0.0.6 still has the same problem.

``` json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "superagent": "^1.8.3",
    "superagent-throttle": "0.0.6"
  }
}
```

``` js
var request = require('superagent');
var Throttle = require('superagent-throttle');

var throttle = new Throttle({
  active: true,
  rate: 5,
  ratePer: 10000,
  concurrent: 2
});

var req = request
  .get('http://placekitten.com/300/100')
  .use(throttle.plugin)
  .end(function(err, res) {
    console.log(err ? err : 'retrieved ' + iteration);
  });

req.abort();
```

**Comment by leviwheatcroft** [comment]
your example works in v0.0.7
Thanks for your help with this.
