### ISSUE TITLE
sending a lot of requests concurrently causes "double callback!" warning

### ISSUE THREAD

**Issue by yocontra** [leviwheatcroft/superagent-throttle#6]
warning is from superagent and shouldn't happen unless something internally got goofed

**Comment by leviwheatcroft** [comment]
Ok, I'll try to reproduce. I've not seen this in any of my own projects, could you give me a little more detail? Like how many is "a lot" ?

**Comment by yocontra** [comment]
@leviwheatcroft 

``` js
import request from 'superagent'
import Throttle from 'superagent-throttle'

const throttle = new Throttle({
  rate: 10000, // how many requests can be sent every `ratePer`
  ratePer: 100, // number of ms in which `rate` requests may be sent
  concurrent: 2000 // how many requests can be sent concurrently
})
const make = (endpoint, data, cb) => {
  request.post(endpoint)
    .use(throttle.plugin())
    .send(data)
    .timeout(3000)
    .end((err, res) => {
      // retry
      if (err && (err.code === 'ECONNABORTED' || err.code === 'ECONNRESET')) {
        return make(endpoint, data, cb)
      }
      if (err) return cb(err)
      if (!res || !res.body) return cb(new Error('No response'))
      if (res.error || res.body.error) return cb(res.body)
      cb(null, res.body)
    })
}

export default make
```

**Comment by leviwheatcroft** [comment]
I've tested this extensively but I've been unable to throw a double callback error / warning.

I've just pushed 0.2.0, and most of the changes were to allow for more insightful debugging to try to identify what may cause this. The unit tests included in this version spool up a tiny server, and even my clunky dev machine can get through about 400 requests per second, apparently without issue.

[This gist](https://gist.github.com/leviwheatcroft/8c42fe0bca6591f333bae0b41de7636e) includes your code above, and sends 20,000 requests, but doesn't throw any warning or error.

**Comment by yocontra** [comment]
@leviwheatcroft Sure - 500 isn't enough to reproduce. Anywhere above 2K reproduces this for me, try sending a few 100K requests. Better yet, set everything to Infinity and it should happen.

**Comment by leviwheatcroft** [comment]
I'd really like to close this issue...

 * I've never been able to reproduce 
 * no one else has reported anything similar
 * code base has changed significantly since issue was posted

In addition, tests included in the package have improved. If this issue still exists then you should be able to play around with "resource bound" test to reproduce.

**Comment by yocontra** [comment]
I haven't seen this in a while so I'm assuming it was fixed here or in superagent itself, I'll close it.
