### ISSUE TITLE
Suggestion: removing lodash / underscore dependency

### ISSUE THREAD

**Issue by mateuszgachowski** [leviwheatcroft/superagent-throttle#7]
What do you think about removing the dependency?
Underscore methods are used like 3-4 times in the source code but you need the whole dependency - I would suggest to replace them with native JS to get rid of this dep.

What do you think? If you agree I can make a PR.

**Comment by leviwheatcroft** [comment]
An excellent suggestion, I'd happily accept a PR if you're happy to do that.

**Comment by leviwheatcroft** [comment]
I've removed the extraneous dependencies in 0.2.0
